# NOTE: Please note that this is just an example of the advanced configuration for the KISS-ICP
# pipeline and it's not really meant to use for any particular dataset, is just to expose other
# options that are disabled by default

kiss_icp_node:
  ros__parameters:
    publish_debug_clouds: true
  
    cable:
      use_anchor: true
      gravity_dir: [0.0, 0.0, 1.0]
      sigma0: 0.02
      kappa: 0.002
      anchor_scale: 1.0
      buffer_seconds: 2.0
      
    data:
      deskew: true
      max_range: 10.0
      min_range: 0.1

    mapping:
      voxel_size: 0.03 # <- optional, default = max_range / 100.0
      max_points_per_voxel: 20

    adaptive_threshold:
      fixed_threshold: 0.01 # <- optional, disables adaptive threshold
      initial_threshold: 0.01
      min_motion_th: 0.1

    registration:
      max_num_iterations: 500 # <- optional
      convergence_criterion: 0.0001 # <- optional
      max_num_threads: 0 # <- optional, 0 means automatic
